-- Find total customer by country
-- Find total customer by gender
-- Find total product by category
-- What is the avg cost by each category?
-- What is the total revenue generated by each category?
-- Find revenue generated by each customer
-- What is the distribution of sold items across by country?

-- Find total customer by country
SELECT DB_NAME();

SELECT country from Cash.dim_customers

SELECT 
	country, 
	count (customer_key) as total_customer 
from Cash.dim_customers
GROUP BY country
ORDER BY total_customer DESC

-- Find total customer by gender
SELECT
	gender,
	COUNT(customer_key) as total_customer
FROM Cash.dim_customers
GROUP BY gender

-- Find total product by category
SELECT
	category, 
	subcategory,
	COUNT(product_name) AS total_product
FROM Cash.dim_products
GROUP BY category, subcategory
ORDER BY category, subcategory DESC

-- What is the avg cost by each category?
SELECT 
	category,
	AVG(cost) as avg_cost
FROM Cash.dim_products
GROUP BY category

-- What is the total revenue generated by each category?
SELECT 
	category,
	SUM(sales_amount) as total_revenue
FROM Cash.fact_sales fs, Cash.dim_products dp
WHERE fs.product_key = dp.product_key
GROUP BY category

SELECT
	d.category,
	SUM(f.sales_amount) AS total_revenue
FROM cash.fact_sales f
LEFT JOIN cash.dim_products d
ON f.product_key = d.product_key
GROUP BY d.category
ORDER BY total_revenue DESC


-- Find revenue generated by each customer
SELECT 
	ds.customer_id,
	ds.first_name,
	ds.last_name,
	SUM(fs.price) as revenue_per_person
FROM cash.fact_sales fs
LEFT JOIN cash.dim_customers ds
ON fs.customer_key = ds.customer_key
GROUP BY 
	ds.customer_id,
	ds.first_name,
	ds.last_name
ORDER BY revenue_per_person DESC


-- What is the distribution of sold items across by country?
SELECT 
	ds.country,
	SUM(fs.quantity) as total_quantity
FROM cash.fact_sales fs
LEFT JOIN cash.dim_customers ds
ON fs.customer_key = ds.customer_key
GROUP BY ds.country
ORDER BY total_quantity DESC

--RANKING
--Which 5 products generate highest revenue?
SELECT TOP 5
ds.product_name,
SUM(fs.sales_amount) Total_revenue
FROM cash.fact_sales fs
LEFT JOIN Cash.dim_products ds
ON fs.product_key = ds.product_key
GROUP BY product_name
ORDER BY Total_revenue DESC

-- What are the 5 worst-performing products in terms of sales?
SELECT TOP 5
ds.product_name,
SUM(fs.sales_amount) Total_revenue
FROM cash.fact_sales fs
LEFT JOIN Cash.dim_products ds
ON fs.product_key = ds.product_key
GROUP BY product_name
ORDER BY Total_revenue 

--Who are the 5 best sellers?
SELECT TOP 5
    ds.first_name,
    ds.last_name,
    ds.customer_id,
    SUM(fs.price) AS total_sales
FROM cash.fact_sales fs
LEFT JOIN cash.dim_customers ds
    ON fs.customer_key = ds.customer_key
GROUP BY 
    ds.first_name,
    ds.last_name,
    ds.customer_id
ORDER BY 
    total_sales DESC;

--Who are the 5 worst sellers?
SELECT TOP 5
    ds.first_name,
    ds.last_name,
    ds.customer_id,
    SUM(fs.price) AS total_sales
FROM cash.fact_sales fs
LEFT JOIN cash.dim_customers ds
    ON fs.customer_key = ds.customer_key
GROUP BY 
    ds.first_name,
    ds.last_name,
    ds.customer_id
ORDER BY 
    total_sales;

--What are the ranks of top products in sale?
SELECT
ds.product_name,
SUM(fs.sales_amount) Total_revenue,
ROW_NUMBER() OVER (ORDER BY SUM(fs.sales_amount) DESC) AS Ranking
FROM cash.fact_sales fs
LEFT JOIN Cash.dim_products ds
ON fs.product_key = ds.product_key
GROUP BY product_name

-- top 5 ranking products (using window function)
SELECT *
from	
	(SELECT 
	ds.product_name,
	SUM(fs.sales_amount) Total_revenue,
	ROW_NUMBER() OVER (ORDER BY SUM(fs.sales_amount) DESC) AS Ranking
	FROM cash.fact_sales fs
	LEFT JOIN Cash.dim_products ds
	ON fs.product_key = ds.product_key
	GROUP BY product_name)t
WHERE Ranking<=5
 


--find the top 10 customers who have generated highest revenue
SELECT top 10
	ds.customer_id,
	ds.first_name,
	ds.last_name,
	SUM(fs.price) as revenue_per_person
FROM cash.fact_sales fs
LEFT JOIN cash.dim_customers ds
ON fs.customer_key = ds.customer_key
GROUP BY 
	ds.customer_id,
	ds.first_name,
	ds.last_name
ORDER BY revenue_per_person DESC

--find the lowest 3 customers who have purchased less
SELECT top 3
	ds.customer_id,
	ds.first_name,
	ds.last_name,
	COUNT(DISTINCT fs.order_number) as Total_orders
FROM cash.fact_sales fs
LEFT JOIN cash.dim_customers ds
ON fs.customer_key = ds.customer_key
GROUP BY 
	ds.customer_id,
	ds.first_name,
	ds.last_name
ORDER BY Total_orders 